### ISSUE TITLE
python setup.py install not working?

### ISSUE THREAD

**Issue by HadXu** [aaronkollasch/seqdesign-pytorch#1]
(seqdesign) [root@xxx seqdesign-pytorch]# python setup.py install
running install
running bdist_egg
running egg_info
writing seqdesign_pt.egg-info/PKG-INFO
writing dependency_links to seqdesign_pt.egg-info/dependency_links.txt
writing top-level names to seqdesign_pt.egg-info/top_level.txt
reading manifest file 'seqdesign_pt.egg-info/SOURCES.txt'
writing manifest file 'seqdesign_pt.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/run_autoregressive_fr -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/generate_sample_seqs_fr -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/calc_logprobs_seqs_fr -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/run_autoregressive_fr to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/generate_sample_seqs_fr to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/calc_logprobs_seqs_fr to 755
copying seqdesign_pt.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying seqdesign_pt.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying seqdesign_pt.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying seqdesign_pt.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/seqdesign_pt-1.0.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing seqdesign_pt-1.0.0-py3.7.egg
Removing /root/anaconda3/envs/seqdesign/lib/python3.7/site-packages/seqdesign_pt-1.0.0-py3.7.egg
Copying seqdesign_pt-1.0.0-py3.7.egg to /root/anaconda3/envs/seqdesign/lib/python3.7/site-packages
seqdesign-pt 1.0.0 is already the active version in easy-install.pth
Installing calc_logprobs_seqs_fr script to /root/anaconda3/envs/seqdesign/bin
Installing generate_sample_seqs_fr script to /root/anaconda3/envs/seqdesign/bin
Installing run_autoregressive_fr script to /root/anaconda3/envs/seqdesign/bin

Installed /root/anaconda3/envs/seqdesign/lib/python3.7/site-packages/seqdesign_pt-1.0.0-py3.7.egg
Processing dependencies for seqdesign-pt==1.0.0
Finished processing dependencies for seqdesign-pt==1.0.0
(seqdesign) [xxxxxxxx]# run_autoregressive_fr
Traceback (most recent call last):
  File "/root/anaconda3/envs/seqdesign/bin/run_autoregressive_fr", line 4, in <module>
    __import__('pkg_resources').run_script('seqdesign-pt==1.0.0', 'run_autoregressive_fr')
  File "/root/anaconda3/envs/seqdesign/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/anaconda3/envs/seqdesign/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/root/anaconda3/envs/seqdesign/lib/python3.7/site-packages/seqdesign_pt-1.0.0-py3.7.egg/EGG-INFO/scripts/run_autoregressive_fr", line 2, in <module>
    # EASY-INSTALL-SCRIPT: 'seqdesign-pt==1.0.0','run_autoregressive_fr'
ModuleNotFoundError: No module named 'seqdesign_pt'

install not working.

**Comment by aaronkollasch** [comment]
Hi,
Thanks for reporting!
The issue is now fixed by #2.
