### ISSUE TITLE
Pytorch vs tensorflow?

### ISSUE THREAD

**Issue by kimdn** [aaronkollasch/seqdesign-pytorch#4]
Readme of 
https://github.com/aaronkollasch/seqdesign-pytorch#seqdesign
says

```

> This version of the codebase is compatible with Python 3 and PyTorch....
> A TensorFlow version is available here

```

Then, why 
`https://github.com/aaronkollasch/seqdesign-pytorch/blob/v3/INSTALL.md`
requires tf installation?

`https://github.com/aaronkollasch/seqdesign-pytorch/blob/v3/src/seqdesign_pt/scripts/calc_logprobs_seqs_fr.py`
appears to import tf as well?

**Comment by aaronkollasch** [comment]
For compatibility with models trained in the tensorflow version, there is a `TFReader` class that imports tensorflow (https://github.com/aaronkollasch/seqdesign-pytorch/blob/v3/src/seqdesign_pt/tf_reader.py). Everything else uses PyTorch.

https://github.com/aaronkollasch/seqdesign-pytorch/blob/ef73865ea51972b5b47bf578da9e03aacbee4455/src/seqdesign_pt/scripts/calc_logprobs_seqs_fr.py#L2 is not strictly necessary, though tensorflow is still imported in that script when `TFReader` is [imported](https://github.com/aaronkollasch/seqdesign-pytorch/blob/ef73865ea51972b5b47bf578da9e03aacbee4455/src/seqdesign_pt/scripts/calc_logprobs_seqs_fr.py#L15). If you wanted to run the code in an environment without tensorflow, you could remove those lines, as well as the tensorflow [version check](https://github.com/aaronkollasch/seqdesign-pytorch/blob/ef73865ea51972b5b47bf578da9e03aacbee4455/src/seqdesign_pt/scripts/calc_logprobs_seqs_fr.py#L49).

The same is true for `generate_sample_seqs_fr.py` but not `run_autoregressive_fr.py` – I could remove tensorflow imports from that script.
